swagger: "2.0"
info:
  title: "Desafio Node.js - Documentação"
  description: "Esta é a documentação da API desenvolvida durante o desafio."
  version: "1.0.0"
  contact:
    telephone: "+5562993063269"
    email: "leonardojr410@gmail.com"
tags: 
  - name: "Usuários"
    description: "Operações dos usuários"
paths:
  /users:
    post:
      tags:
        - "Usuários"
      summary: "Criar um usuário"
      description: "Cria um usuário"
      parameters:
        - in: "body"
          name: "body"
          description: "Informações do usuário"
          required: true 
          schema:
            $ref: "#/definitions/CreateUser"
      responses:
        201:
          description: "Usuário criado"
        400:
          description: "Erro de validação"
    get:
      tags:
        - "Usuários"
      summary: "Listar usuários"
      description: "Lista todos os usuários"
      parameters:
        - name: "displayName"
          description: 'Lista os usuários que tem o texto informado no campo "displayName"'
          in: "query"
        - name: "email"
          description: 'Lista os usuários que tem o texto informado no campo "email"'
          in: "query"
        - name: "page"
          description: 'Número da página (deve ser usada junto com o "limit" e ser maior que 0)'
          in: "query"
        - name: "limit"
          description: 'Limite de usuários retornados (deve ser usada junto com a "page" e ser maior que 0)'
          in: "query"
      responses:
        200:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/definitions/FindUsersResponse"
  /users/{id}:
    get:
      tags:
        - "Usuários"
      summary: "Listar usuário por id"
      description: "Lista o usuário pelo o id informado"
      parameters:
        - name: "id"
          description: "O id do usuário a ser consultado"
          in: "path"
          required: true
      responses:
        200:
          description: "Sucesso"
          content:
            application/json:
              schema:
                $ref: "#/definitions/User"
        404:
          description: "Usuário não encontrado"
        400:
          description: "Id inválido"
    patch:
      tags:
        - "Usuários"
      summary: "Alterar usuário por id"
      description: "Altera as informações do usuário através de seu id"
      parameters:
        - name: "id"
          description: "O id do usuário a ser alterado"
          in: "path"
          required: true
        - in: "body"
          name: "body"
          description: "Informações do usuário que serão alteradas"
          required: true 
          schema:
            $ref: "#/definitions/UpdateUser"
      responses:
        200:
          description: "Sucesso"
        404:
          description: "Usuário não encontrado"
        400:
          description: "Erro de validação"
    delete:
      tags:
        - "Usuários"
      summary: "Deletar usuário por id"
      description: "Deleta o usuário através de seu id"
      parameters:
        - name: "id"
          description: "O id do usuário a ser deletado"
          in: "path"
          required: true
      responses:
        204:
          description: "Sucesso"
        404:
          description: "Usuário não encontrado"
        400:
          description: "Id inválido"
definitions:
  CreateUser:
    type: "object"
    properties:
      displayName:
        type: "string"
        description: "O nome do usuário"
        example: "Leonardo Jardim Ribeiro"
        required: true
      email:
        type: "string"
        description: "O email do usuário (deve ser único)"
        example: "leonardojr410@gmail.com"
        required: true
      password:
        type: "string"
        description: "A senha do usuário (deve ter pelo menos 6 caracteres)"
        required: true
      birthDate:
        type: "string"
        description: "A data de nascimento do usuário (deve estar no formato ISO 8601 e o tempo entre ela e a data atual de 18 anos)"
        example: "1998-06-25"
        required: true
      photoUrl:
        type: "string"
        description: "A foto do usuário"
  FindUsersResponse:
    type: "object"
    properties:
      usersCount:
        type: "integer"
        description: "A quantidade total de usuário que satisfazeram a pesquisa"
      users:
        type: "array"
        items:
          $ref: "#/definitions/User"
  User:
    type: "object"
    properties:
      id:
        type: "string"
        description: "O id do usuário"
      displayName:
        type: "string"
        description: "O nome do usuário"
      email:
        type: "string"
        description: "O email do usuário"
      birthDate:
        type: "string"
        description: "A data de nascimento do usuário"
      photoUrl:
        type: "string"
        description: "A foto do usuário"
  UpdateUser:
    type: "object"
    properties:
      displayName:
        type: "string"
        description: "O nome do usuário"
        example: "Leonardo Jardim Ribeiro"
      email:
        type: "string"
        description: "O email do usuário (deve ser único)"
        example: "leonardojr410@gmail.com"
      password:
        type: "string"
        description: "A senha do usuário (deve ter pelo menos 6 caracteres)"
      birthDate:
        type: "string"
        description: "A data de nascimento do usuário (deve estar no formato ISO 8601 e o tempo entre ela e a data atual de 18 anos)"
        example: "1998-06-25"
      photoUrl:
        type: "string"
        description: "A foto do usuário"
