services:
  mongodb:
    image: mongo
    restart: always
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    volumes:
      - mongodb:/data/db

  app:
    build: .
    restart: always
    container_name: desafioNode
    environment:
      - MONGO_URL=mongodb://root:root@mongodb:27017/node_challenge?authSource=admin
    ports:
      - 3000:3000
    volumes:
      - .:/usr/application
      - /usr/application/node_modules
    links:
      - mongodb
volumes:
  mongodb:


